### ISSUE TITLE
Create dev DB

### ISSUE THREAD

**Issue by Donovanphenry** [Donovanphenry/BBFL#1]
It's currently difficult to test out changes involving the backend. To do so, it's necessary to modify the production DB, which is rather destructive testing. In an ideal world, the development environment and production environment are isolated, and unaware of one-another.

We should find a way to create this isolation. There are a few options here:
1. Add a column to one of the associated production table that flags whether or not the pick/user is a testing selection. Then, in the production front-end, ignore picks/users with this flag selected.
2. Create a dev `user_picks` table and change the table that the front-end communicates with based on the active mode.

There are likely to be other solutions available. But I imagine they will all be of the forms:
1. Flag that production should ignore a testing pick and dev should not
2. Create isolated environment (in the form of a new table, most likely) that prod doesn't interact with and dev does

IMO, better developer standards would probably mean selecting option `#2`. Again, prod and development environments should be completely distinct, and `#1` violates this. But it would probably be marginally easier to solve this that way.

**Comment by ZachJGreen** [comment]
ebic 50044d63c2192d3b26b39c478c2fb158b42110ef
