### ISSUE TITLE
Button coloring bug on login page

### ISSUE THREAD

**Issue by Donovanphenry** [Donovanphenry/BBFL#3]
On the login page, there is a UI bug on windows, it seems. The color of the text for a few of the buttons are the same as the background of the button itself. In turn, it's impossible to know what the buttons do.

We should fix the coloring, and figure out why it's going wrong in the first place.

The relevant files are under `BBFL/src/components/LoginModal/`.

**Comment by Donovanphenry** [comment]
Fixerd

**Comment by ZachJGreen** [comment]
fixed with cca726897f330a475863054964decf3ca76fa5bf
