### ISSUE TITLE
Lock down submissions after games are considered "late"

### ISSUE THREAD

**Issue by Donovanphenry** [Donovanphenry/BBFL#4]
Players should not be allowed to submit picks after games have started. We currently have *selections* locked down after games have started. I.e., after a match has begun, users can no longer select a change for that match. However, it's possible for a user to load up changes before the matches have started, wait for the games to start, and then notice that their team is losing. Then they submit their pick and the DB is none the wiser.

We should add a layer of security to the `Submit Changes` button, ensure that `BBFL/src/components/NFL/NFL.jsx::NFL::submit_picks` cannot render changes after a match is considered `late`.

Alternatively, figure out a way to lock things down in the database as opposed to in the front-end.

**Comment by ZachJGreen** [comment]
fixed with 82e4e1481d5c20abd20d36dbda4659c6d7635374
