### ISSUE TITLE
Come up with different way of notifying user that their picks have been submitted

### ISSUE THREAD

**Issue by Donovanphenry** [Donovanphenry/BBFL#9]
When a user selects their choices, and submits their picks, we need a way to let them know that work is being done in the database. if nothing happens after they click the button, they will likely spam click the button pointlessly, refresh the page, or carry out other sanity checks to verify their picks have been submitted. We currently carry out this sanity check for them by simply refreshing the page. However, this is a bit of a heavy hammer.

Perhaps we can create a banner notifying them that their changes have been saved to the database, or whatever other notification you can think of.

**Comment by ZachJGreen** [comment]
fixed with 82e4e1481d5c20abd20d36dbda4659c6d7635374
